<?php if ($this->pageCount): ?> 
<div class="paginationControl">
<!-- Previous page link --> 
<?php if (isset($this->previous)): ?> 
  <span class="googlenav"><a href="<?= $this->url(array('page' => $this->previous)); ?>">&laquo; Previous</a> </span>
<?php else: ?> 
  <span class="disabled">&laquo; Previous</span>
<?php endif; ?> 

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?> 
  <?php if ($page != $this->current): ?>
    <span class="googlenav"><a href="<?= $this->url(array('page' => $page)); ?>"><?= $page; ?></a> </span> 
  <?php else: ?>
    <span class="current"><?= $page; ?></span>
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link --> 
<?php if (isset($this->next)): ?> 
  <span class="googlenav"><a href="<?= $this->url(array('page' => $this->next)); ?>">Next &raquo;</a></span>
<?php else: ?> 
  <span class="disabled">Next &gt;</span>
<?php endif; ?> 
</div> 
<?php endif; ?> 