<script type="text/javascript">

	  $( function(){ 
		$("table.zebra tr:even").addClass("even"); 
		$("table.zebra tr:odd").addClass("odd"); 
		});
</script>
<style>
.window-div
{
	height:400px;
	border:1px solid;
	overflow:scroll;
}
.div1
{
	width:200px;
}
</style>

<div class="div1">
	
</div>

<!-- <div class="window-div">
<table class="zebra">
<?php
/*foreach($this->data as $row)
{
	echo "<tr><td>".$row."</td></tr>";
}*/
?>
</table>
</div>  -->