
<?php
$header=array($this->tableHeader['schemeId'], $this->tableHeader['empId'], $this->tableHeader['custId'], 
$this->tableHeader['transId'], $this->tableHeader['firstPayDt'], $this->tableHeader['lastPayDt'], 
$this->tableHeader['ageInDays'], $this->tableHeader['totalPayment'],$this->tableHeader['totalReceipt'],
$this->tableHeader['paymentAmount'], $this->tableHeader['receiptAmount'],$this->tableHeader['dueAmount']);

$filename="report3_".$this->fileno;
$this->createExcelReport($filename,$header,$this->reports);
?>